services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./client:/client
      - /client/node_modules
    command: npm run dev -- --host 0.0.0.0 --port 5173
    environment:
      - CHOKIDAR_USEPOLLING=true
  server:
    depends_on:
      - db
    build:
      context: ./server
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: labradml
      DB_PASS: pass
      DB_NAME: chatterbox_db
      ACCESS_TOKEN: 5088f4937e3ac86e57f1a3dfd422a72ce8be8d62070d0f38d30e7a563ee78cf5edfd93b73060a3f42ea981401569ff70fc7d12c71ecd4367cb19ee9ebb9f08de
      REFRESH_TOKEN: 75d391935b3e1c4ae4e9299b3b513f611751bf620ea2d149b361537d096f1525971b1054bf7ba75ad0b6fb95f90649787fb307108f8a0b7d8186eca265f21c89
    develop:
      watch:
        - action: sync
          path: ./server/src
          target: /server/src
          initial_sync: true
          ignore:
            - node_modules/
        - action: rebuild
          path: ./server/package.json
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: labradml
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: chatterbox_db
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: